name: CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.6

      - name: Terraform Init and Validate
        working-directory: terraform
        run: |
          terraform init
          terraform validate

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      - name: Create Kind Cluster
        run: |
          kind create cluster --name verkstedt-cluster

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'

      - name: Pre-pull nginx image into Kind
        run: |
          docker pull nginx:latest
          kind load docker-image nginx:latest

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f secrets/
          kubectl apply -f k8s/

      - name: Wait for Deployments to be Ready
        continue-on-error: true
        run: |
          kubectl wait --for=condition=available --timeout=180s deployment/nginx -n verkstedt-demo
          kubectl wait --for=condition=available --timeout=180s deployment/postgres -n verkstedt-demo
          kubectl wait --for=condition=available --timeout=180s deployment/prometheus -n verkstedt-demo
          kubectl wait --for=condition=available --timeout=180s deployment/grafana -n verkstedt-demo

      - name: Debug NGINX Deployment Status
        run: |
          echo "🧪 Pods in verkstedt-demo:"
          kubectl get pods -n verkstedt-demo -o wide || true

          echo "📋 Events:"
          kubectl get events -n verkstedt-demo --sort-by=.metadata.creationTimestamp || true

          echo "🔍 Describe NGINX deployment:"
          kubectl describe deployment nginx -n verkstedt-demo || true

          echo "📦 Logs from the NGINX pod:"
          POD=$(kubectl get pods -n verkstedt-demo -l app=nginx -o jsonpath="{.items[0].metadata.name}" 2>/dev/null || echo "")
          if [ -n "$POD" ]; then
            kubectl logs "$POD" -n verkstedt-demo || true
          else
            echo "⚠️ No NGINX pod found."
          fi

      - name: Check for Pending Pods
        run: |
          echo "Pending pod details:"
          kubectl get pods -n verkstedt-demo -o name | xargs -r kubectl describe -n verkstedt-demo || true

      - name: Cleanup Kubernetes Resources
        run: |
          kubectl delete namespace verkstedt-demo --ignore-not-found=true

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve
