apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: verkstedt-demo
type: Opaque
data:
  username: cG9zdGdyZXM=  # base64 of 'postgres'
  password: c2VjdXJlcGFzc3dvcmQ=  # base64 of 'securepassword'
